// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.Address)
    com.google.protobuf.MessageOrBuilder {
}
