// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package animals;

public final class AnimalOuterClass {
  private AnimalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_animals_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_animals_Animal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014animal.proto\022\007animals\"$\n\006Animal\022\014\n\004nam" +
      "e\030\001 \001(\t\022\014\n\004hunt\030\002 \001(\010B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_animals_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_animals_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_animals_Animal_descriptor,
        new java.lang.String[] { "Name", "Hunt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
