// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package animals;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool hunt = 2;</code>
   * @return The hunt.
   */
  boolean getHunt();
}
