// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

/**
 * Protobuf type {@code animals.Lion}
 */
public final class Lion extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:animals.Lion)
    LionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Lion.newBuilder() to construct.
  private Lion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Lion() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Lion();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Lion(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 16: {

            capacity_ = input.readInt32();
            break;
          }
          case 24: {

            id_ = input.readInt32();
            break;
          }
          case 34: {
            animals.Animal.Builder subBuilder = null;
            if (animalObject_ != null) {
              subBuilder = animalObject_.toBuilder();
            }
            animalObject_ = input.readMessage(animals.Animal.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(animalObject_);
              animalObject_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return animals.LionOuterClass.internal_static_animals_Lion_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return animals.LionOuterClass.internal_static_animals_Lion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            animals.Lion.class, animals.Lion.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPACITY_FIELD_NUMBER = 2;
  private int capacity_;
  /**
   * <code>int32 capacity = 2;</code>
   * @return The capacity.
   */
  @java.lang.Override
  public int getCapacity() {
    return capacity_;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private int id_;
  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int ANIMALOBJECT_FIELD_NUMBER = 4;
  private animals.Animal animalObject_;
  /**
   * <code>.animals.Animal animalObject = 4;</code>
   * @return Whether the animalObject field is set.
   */
  @java.lang.Override
  public boolean hasAnimalObject() {
    return animalObject_ != null;
  }
  /**
   * <code>.animals.Animal animalObject = 4;</code>
   * @return The animalObject.
   */
  @java.lang.Override
  public animals.Animal getAnimalObject() {
    return animalObject_ == null ? animals.Animal.getDefaultInstance() : animalObject_;
  }
  /**
   * <code>.animals.Animal animalObject = 4;</code>
   */
  @java.lang.Override
  public animals.AnimalOrBuilder getAnimalObjectOrBuilder() {
    return getAnimalObject();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (capacity_ != 0) {
      output.writeInt32(2, capacity_);
    }
    if (id_ != 0) {
      output.writeInt32(3, id_);
    }
    if (animalObject_ != null) {
      output.writeMessage(4, getAnimalObject());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (capacity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, capacity_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, id_);
    }
    if (animalObject_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAnimalObject());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof animals.Lion)) {
      return super.equals(obj);
    }
    animals.Lion other = (animals.Lion) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (getCapacity()
        != other.getCapacity()) return false;
    if (getId()
        != other.getId()) return false;
    if (hasAnimalObject() != other.hasAnimalObject()) return false;
    if (hasAnimalObject()) {
      if (!getAnimalObject()
          .equals(other.getAnimalObject())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + CAPACITY_FIELD_NUMBER;
    hash = (53 * hash) + getCapacity();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasAnimalObject()) {
      hash = (37 * hash) + ANIMALOBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalObject().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static animals.Lion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals.Lion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals.Lion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals.Lion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals.Lion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static animals.Lion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static animals.Lion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static animals.Lion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(animals.Lion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code animals.Lion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:animals.Lion)
      animals.LionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return animals.LionOuterClass.internal_static_animals_Lion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return animals.LionOuterClass.internal_static_animals_Lion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              animals.Lion.class, animals.Lion.Builder.class);
    }

    // Construct using animals.Lion.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      capacity_ = 0;

      id_ = 0;

      if (animalObjectBuilder_ == null) {
        animalObject_ = null;
      } else {
        animalObject_ = null;
        animalObjectBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return animals.LionOuterClass.internal_static_animals_Lion_descriptor;
    }

    @java.lang.Override
    public animals.Lion getDefaultInstanceForType() {
      return animals.Lion.getDefaultInstance();
    }

    @java.lang.Override
    public animals.Lion build() {
      animals.Lion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public animals.Lion buildPartial() {
      animals.Lion result = new animals.Lion(this);
      result.type_ = type_;
      result.capacity_ = capacity_;
      result.id_ = id_;
      if (animalObjectBuilder_ == null) {
        result.animalObject_ = animalObject_;
      } else {
        result.animalObject_ = animalObjectBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof animals.Lion) {
        return mergeFrom((animals.Lion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(animals.Lion other) {
      if (other == animals.Lion.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getCapacity() != 0) {
        setCapacity(other.getCapacity());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasAnimalObject()) {
        mergeAnimalObject(other.getAnimalObject());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      animals.Lion parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (animals.Lion) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int capacity_ ;
    /**
     * <code>int32 capacity = 2;</code>
     * @return The capacity.
     */
    @java.lang.Override
    public int getCapacity() {
      return capacity_;
    }
    /**
     * <code>int32 capacity = 2;</code>
     * @param value The capacity to set.
     * @return This builder for chaining.
     */
    public Builder setCapacity(int value) {
      
      capacity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 capacity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapacity() {
      
      capacity_ = 0;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private animals.Animal animalObject_;
    private com.google.protobuf.SingleFieldBuilderV3<
        animals.Animal, animals.Animal.Builder, animals.AnimalOrBuilder> animalObjectBuilder_;
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     * @return Whether the animalObject field is set.
     */
    public boolean hasAnimalObject() {
      return animalObjectBuilder_ != null || animalObject_ != null;
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     * @return The animalObject.
     */
    public animals.Animal getAnimalObject() {
      if (animalObjectBuilder_ == null) {
        return animalObject_ == null ? animals.Animal.getDefaultInstance() : animalObject_;
      } else {
        return animalObjectBuilder_.getMessage();
      }
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    public Builder setAnimalObject(animals.Animal value) {
      if (animalObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animalObject_ = value;
        onChanged();
      } else {
        animalObjectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    public Builder setAnimalObject(
        animals.Animal.Builder builderForValue) {
      if (animalObjectBuilder_ == null) {
        animalObject_ = builderForValue.build();
        onChanged();
      } else {
        animalObjectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    public Builder mergeAnimalObject(animals.Animal value) {
      if (animalObjectBuilder_ == null) {
        if (animalObject_ != null) {
          animalObject_ =
            animals.Animal.newBuilder(animalObject_).mergeFrom(value).buildPartial();
        } else {
          animalObject_ = value;
        }
        onChanged();
      } else {
        animalObjectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    public Builder clearAnimalObject() {
      if (animalObjectBuilder_ == null) {
        animalObject_ = null;
        onChanged();
      } else {
        animalObject_ = null;
        animalObjectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    public animals.Animal.Builder getAnimalObjectBuilder() {
      
      onChanged();
      return getAnimalObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    public animals.AnimalOrBuilder getAnimalObjectOrBuilder() {
      if (animalObjectBuilder_ != null) {
        return animalObjectBuilder_.getMessageOrBuilder();
      } else {
        return animalObject_ == null ?
            animals.Animal.getDefaultInstance() : animalObject_;
      }
    }
    /**
     * <code>.animals.Animal animalObject = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        animals.Animal, animals.Animal.Builder, animals.AnimalOrBuilder> 
        getAnimalObjectFieldBuilder() {
      if (animalObjectBuilder_ == null) {
        animalObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            animals.Animal, animals.Animal.Builder, animals.AnimalOrBuilder>(
                getAnimalObject(),
                getParentForChildren(),
                isClean());
        animalObject_ = null;
      }
      return animalObjectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:animals.Lion)
  }

  // @@protoc_insertion_point(class_scope:animals.Lion)
  private static final animals.Lion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new animals.Lion();
  }

  public static animals.Lion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Lion>
      PARSER = new com.google.protobuf.AbstractParser<Lion>() {
    @java.lang.Override
    public Lion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Lion(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Lion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Lion> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public animals.Lion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

