// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

public interface LionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.Lion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 capacity = 2;</code>
   * @return The capacity.
   */
  int getCapacity();

  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.animals.Animal animalObject = 4;</code>
   * @return Whether the animalObject field is set.
   */
  boolean hasAnimalObject();
  /**
   * <code>.animals.Animal animalObject = 4;</code>
   * @return The animalObject.
   */
  animals.Animal getAnimalObject();
  /**
   * <code>.animals.Animal animalObject = 4;</code>
   */
  animals.AnimalOrBuilder getAnimalObjectOrBuilder();
}
