// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

public interface LionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.Lion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getMap();
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getMapMap();
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */

  int getMapOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */

  int getMapOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;int32, .animals.Lion.IntegerList&gt; pairs = 2;</code>
   */
  int getPairsCount();
  /**
   * <code>map&lt;int32, .animals.Lion.IntegerList&gt; pairs = 2;</code>
   */
  boolean containsPairs(
      int key);
  /**
   * Use {@link #getPairsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, animals.Lion.IntegerList>
  getPairs();
  /**
   * <code>map&lt;int32, .animals.Lion.IntegerList&gt; pairs = 2;</code>
   */
  java.util.Map<java.lang.Integer, animals.Lion.IntegerList>
  getPairsMap();
  /**
   * <code>map&lt;int32, .animals.Lion.IntegerList&gt; pairs = 2;</code>
   */

  animals.Lion.IntegerList getPairsOrDefault(
      int key,
      animals.Lion.IntegerList defaultValue);
  /**
   * <code>map&lt;int32, .animals.Lion.IntegerList&gt; pairs = 2;</code>
   */

  animals.Lion.IntegerList getPairsOrThrow(
      int key);

  /**
   * <code>map&lt;int32, .animals.Lion.AddressList&gt; pairsM = 3;</code>
   */
  int getPairsMCount();
  /**
   * <code>map&lt;int32, .animals.Lion.AddressList&gt; pairsM = 3;</code>
   */
  boolean containsPairsM(
      int key);
  /**
   * Use {@link #getPairsMMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, animals.Lion.AddressList>
  getPairsM();
  /**
   * <code>map&lt;int32, .animals.Lion.AddressList&gt; pairsM = 3;</code>
   */
  java.util.Map<java.lang.Integer, animals.Lion.AddressList>
  getPairsMMap();
  /**
   * <code>map&lt;int32, .animals.Lion.AddressList&gt; pairsM = 3;</code>
   */

  animals.Lion.AddressList getPairsMOrDefault(
      int key,
      animals.Lion.AddressList defaultValue);
  /**
   * <code>map&lt;int32, .animals.Lion.AddressList&gt; pairsM = 3;</code>
   */

  animals.Lion.AddressList getPairsMOrThrow(
      int key);
}
