// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

public final class LionOuterClass {
  private LionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_animals_Lion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_animals_Lion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nlion.proto\022\007animals\032\014animal.proto\"Y\n\004L" +
      "ion\022\014\n\004type\030\001 \001(\t\022\020\n\010capacity\030\002 \001(\005\022\n\n\002i" +
      "d\030\003 \001(\005\022%\n\014animalObject\030\004 \001(\0132\017.animals." +
      "AnimalB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          animals.AnimalOuterClass.getDescriptor(),
        });
    internal_static_animals_Lion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_animals_Lion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_animals_Lion_descriptor,
        new java.lang.String[] { "Type", "Capacity", "Id", "AnimalObject", });
    animals.AnimalOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
