// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

/**
 * Protobuf type {@code animals.Lion}
 */
public final class Lion extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:animals.Lion)
    LionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Lion.newBuilder() to construct.
  private Lion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Lion() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Lion();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Lion(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              map_ = com.google.protobuf.MapField.newMapField(
                  MapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
            map__ = input.readMessage(
                MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            map_.getMutableMap().put(
                map__.getKey(), map__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              pairs_ = com.google.protobuf.MapField.newMapField(
                  PairsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, animals.FemaleLion>
            pairs__ = input.readMessage(
                PairsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            pairs_.getMutableMap().put(
                pairs__.getKey(), pairs__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return animals.LionOuterClass.internal_static_animals_Lion_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetMap();
      case 2:
        return internalGetPairs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return animals.LionOuterClass.internal_static_animals_Lion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            animals.Lion.class, animals.Lion.Builder.class);
  }

  public static final int MAP_FIELD_NUMBER = 1;
  private static final class MapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                animals.LionOuterClass.internal_static_animals_Lion_MapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> map_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetMap() {
    if (map_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapDefaultEntryHolder.defaultEntry);
    }
    return map_;
  }

  public int getMapCount() {
    return internalGetMap().getMap().size();
  }
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */

  @java.lang.Override
  public boolean containsMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getMap() {
    return getMapMap();
  }
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Integer> getMapMap() {
    return internalGetMap().getMap();
  }
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */
  @java.lang.Override

  public int getMapOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int32&gt; map = 1;</code>
   */
  @java.lang.Override

  public int getMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PAIRS_FIELD_NUMBER = 2;
  private static final class PairsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, animals.FemaleLion> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, animals.FemaleLion>newDefaultInstance(
                animals.LionOuterClass.internal_static_animals_Lion_PairsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                animals.FemaleLion.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, animals.FemaleLion> pairs_;
  private com.google.protobuf.MapField<java.lang.Integer, animals.FemaleLion>
  internalGetPairs() {
    if (pairs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PairsDefaultEntryHolder.defaultEntry);
    }
    return pairs_;
  }

  public int getPairsCount() {
    return internalGetPairs().getMap().size();
  }
  /**
   * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
   */

  @java.lang.Override
  public boolean containsPairs(
      int key) {
    
    return internalGetPairs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPairsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, animals.FemaleLion> getPairs() {
    return getPairsMap();
  }
  /**
   * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, animals.FemaleLion> getPairsMap() {
    return internalGetPairs().getMap();
  }
  /**
   * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
   */
  @java.lang.Override

  public animals.FemaleLion getPairsOrDefault(
      int key,
      animals.FemaleLion defaultValue) {
    
    java.util.Map<java.lang.Integer, animals.FemaleLion> map =
        internalGetPairs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
   */
  @java.lang.Override

  public animals.FemaleLion getPairsOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, animals.FemaleLion> map =
        internalGetPairs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMap(),
        MapDefaultEntryHolder.defaultEntry,
        1);
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetPairs(),
        PairsDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, map__);
    }
    for (java.util.Map.Entry<java.lang.Integer, animals.FemaleLion> entry
         : internalGetPairs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, animals.FemaleLion>
      pairs__ = PairsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pairs__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof animals.Lion)) {
      return super.equals(obj);
    }
    animals.Lion other = (animals.Lion) obj;

    if (!internalGetMap().equals(
        other.internalGetMap())) return false;
    if (!internalGetPairs().equals(
        other.internalGetPairs())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetMap().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMap().hashCode();
    }
    if (!internalGetPairs().getMap().isEmpty()) {
      hash = (37 * hash) + PAIRS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPairs().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static animals.Lion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals.Lion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals.Lion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals.Lion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals.Lion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static animals.Lion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static animals.Lion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static animals.Lion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static animals.Lion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(animals.Lion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code animals.Lion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:animals.Lion)
      animals.LionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return animals.LionOuterClass.internal_static_animals_Lion_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMap();
        case 2:
          return internalGetPairs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableMap();
        case 2:
          return internalGetMutablePairs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return animals.LionOuterClass.internal_static_animals_Lion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              animals.Lion.class, animals.Lion.Builder.class);
    }

    // Construct using animals.Lion.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableMap().clear();
      internalGetMutablePairs().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return animals.LionOuterClass.internal_static_animals_Lion_descriptor;
    }

    @java.lang.Override
    public animals.Lion getDefaultInstanceForType() {
      return animals.Lion.getDefaultInstance();
    }

    @java.lang.Override
    public animals.Lion build() {
      animals.Lion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public animals.Lion buildPartial() {
      animals.Lion result = new animals.Lion(this);
      int from_bitField0_ = bitField0_;
      result.map_ = internalGetMap();
      result.map_.makeImmutable();
      result.pairs_ = internalGetPairs();
      result.pairs_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof animals.Lion) {
        return mergeFrom((animals.Lion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(animals.Lion other) {
      if (other == animals.Lion.getDefaultInstance()) return this;
      internalGetMutableMap().mergeFrom(
          other.internalGetMap());
      internalGetMutablePairs().mergeFrom(
          other.internalGetPairs());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      animals.Lion parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (animals.Lion) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMutableMap() {
      onChanged();;
      if (map_ == null) {
        map_ = com.google.protobuf.MapField.newMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      if (!map_.isMutable()) {
        map_ = map_.copy();
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */

    @java.lang.Override
    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Integer> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */
    @java.lang.Override

    public int getMapOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */
    @java.lang.Override

    public int getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMap() {
      internalGetMutableMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */

    public Builder removeMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getMutableMap() {
      return internalGetMutableMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */
    public Builder putMap(
        java.lang.String key,
        int value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; map = 1;</code>
     */

    public Builder putAllMap(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, animals.FemaleLion> pairs_;
    private com.google.protobuf.MapField<java.lang.Integer, animals.FemaleLion>
    internalGetPairs() {
      if (pairs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PairsDefaultEntryHolder.defaultEntry);
      }
      return pairs_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, animals.FemaleLion>
    internalGetMutablePairs() {
      onChanged();;
      if (pairs_ == null) {
        pairs_ = com.google.protobuf.MapField.newMapField(
            PairsDefaultEntryHolder.defaultEntry);
      }
      if (!pairs_.isMutable()) {
        pairs_ = pairs_.copy();
      }
      return pairs_;
    }

    public int getPairsCount() {
      return internalGetPairs().getMap().size();
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */

    @java.lang.Override
    public boolean containsPairs(
        int key) {
      
      return internalGetPairs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPairsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, animals.FemaleLion> getPairs() {
      return getPairsMap();
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, animals.FemaleLion> getPairsMap() {
      return internalGetPairs().getMap();
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */
    @java.lang.Override

    public animals.FemaleLion getPairsOrDefault(
        int key,
        animals.FemaleLion defaultValue) {
      
      java.util.Map<java.lang.Integer, animals.FemaleLion> map =
          internalGetPairs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */
    @java.lang.Override

    public animals.FemaleLion getPairsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, animals.FemaleLion> map =
          internalGetPairs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPairs() {
      internalGetMutablePairs().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */

    public Builder removePairs(
        int key) {
      
      internalGetMutablePairs().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, animals.FemaleLion>
    getMutablePairs() {
      return internalGetMutablePairs().getMutableMap();
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */
    public Builder putPairs(
        int key,
        animals.FemaleLion value) {
      
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutablePairs().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, .animals.FemaleLion&gt; pairs = 2;</code>
     */

    public Builder putAllPairs(
        java.util.Map<java.lang.Integer, animals.FemaleLion> values) {
      internalGetMutablePairs().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:animals.Lion)
  }

  // @@protoc_insertion_point(class_scope:animals.Lion)
  private static final animals.Lion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new animals.Lion();
  }

  public static animals.Lion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Lion>
      PARSER = new com.google.protobuf.AbstractParser<Lion>() {
    @java.lang.Override
    public Lion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Lion(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Lion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Lion> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public animals.Lion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

