// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lion.proto

package animals;

public interface MaleLionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.MaleLion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
