// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance_1/animal1.proto

package animals1;

public final class Animal1 {
  private Animal1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_animals1_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_animals1_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_animals1_Animal_Tiger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_animals1_Animal_Tiger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033inheritance_1/animal1.proto\022\010animals1\"" +
      "\250\001\n\006Animal\022\014\n\004name\030\001 \001(\t\022\014\n\004hunt\030\002 \001(\010\022%" +
      "\n\005tiger\030\003 \001(\0132\026.animals1.Animal.Tiger\032[\n" +
      "\005Tiger\022\014\n\004type\030\001 \001(\t\022\020\n\010capacity\030\002 \001(\005\022\n" +
      "\n\002id\030\003 \001(\005\022&\n\014animalObject\030\004 \001(\0132\020.anima" +
      "ls1.AnimalB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_animals1_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_animals1_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_animals1_Animal_descriptor,
        new java.lang.String[] { "Name", "Hunt", "Tiger", });
    internal_static_animals1_Animal_Tiger_descriptor =
      internal_static_animals1_Animal_descriptor.getNestedTypes().get(0);
    internal_static_animals1_Animal_Tiger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_animals1_Animal_Tiger_descriptor,
        new java.lang.String[] { "Type", "Capacity", "Id", "AnimalObject", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
