// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance_1/animal1.proto

package animals1;

/**
 * Protobuf type {@code animals1.Animal}
 */
public final class Animal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:animals1.Animal)
    AnimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Animal.newBuilder() to construct.
  private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Animal() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Animal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Animal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            hunt_ = input.readBool();
            break;
          }
          case 26: {
            animals1.Animal.Tiger.Builder subBuilder = null;
            if (tiger_ != null) {
              subBuilder = tiger_.toBuilder();
            }
            tiger_ = input.readMessage(animals1.Animal.Tiger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tiger_);
              tiger_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return animals1.Animal1.internal_static_animals1_Animal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return animals1.Animal1.internal_static_animals1_Animal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            animals1.Animal.class, animals1.Animal.Builder.class);
  }

  public interface TigerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:animals1.Animal.Tiger)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 capacity = 2;</code>
     * @return The capacity.
     */
    int getCapacity();

    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.animals1.Animal animalObject = 4;</code>
     * @return Whether the animalObject field is set.
     */
    boolean hasAnimalObject();
    /**
     * <code>.animals1.Animal animalObject = 4;</code>
     * @return The animalObject.
     */
    animals1.Animal getAnimalObject();
    /**
     * <code>.animals1.Animal animalObject = 4;</code>
     */
    animals1.AnimalOrBuilder getAnimalObjectOrBuilder();
  }
  /**
   * Protobuf type {@code animals1.Animal.Tiger}
   */
  public static final class Tiger extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:animals1.Animal.Tiger)
      TigerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tiger.newBuilder() to construct.
    private Tiger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tiger() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tiger();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tiger(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              capacity_ = input.readInt32();
              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 34: {
              animals1.Animal.Builder subBuilder = null;
              if (animalObject_ != null) {
                subBuilder = animalObject_.toBuilder();
              }
              animalObject_ = input.readMessage(animals1.Animal.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(animalObject_);
                animalObject_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return animals1.Animal1.internal_static_animals1_Animal_Tiger_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return animals1.Animal1.internal_static_animals1_Animal_Tiger_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              animals1.Animal.Tiger.class, animals1.Animal.Tiger.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPACITY_FIELD_NUMBER = 2;
    private int capacity_;
    /**
     * <code>int32 capacity = 2;</code>
     * @return The capacity.
     */
    @java.lang.Override
    public int getCapacity() {
      return capacity_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ANIMALOBJECT_FIELD_NUMBER = 4;
    private animals1.Animal animalObject_;
    /**
     * <code>.animals1.Animal animalObject = 4;</code>
     * @return Whether the animalObject field is set.
     */
    @java.lang.Override
    public boolean hasAnimalObject() {
      return animalObject_ != null;
    }
    /**
     * <code>.animals1.Animal animalObject = 4;</code>
     * @return The animalObject.
     */
    @java.lang.Override
    public animals1.Animal getAnimalObject() {
      return animalObject_ == null ? animals1.Animal.getDefaultInstance() : animalObject_;
    }
    /**
     * <code>.animals1.Animal animalObject = 4;</code>
     */
    @java.lang.Override
    public animals1.AnimalOrBuilder getAnimalObjectOrBuilder() {
      return getAnimalObject();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (capacity_ != 0) {
        output.writeInt32(2, capacity_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (animalObject_ != null) {
        output.writeMessage(4, getAnimalObject());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (capacity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, capacity_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (animalObject_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAnimalObject());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof animals1.Animal.Tiger)) {
        return super.equals(obj);
      }
      animals1.Animal.Tiger other = (animals1.Animal.Tiger) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (getCapacity()
          != other.getCapacity()) return false;
      if (getId()
          != other.getId()) return false;
      if (hasAnimalObject() != other.hasAnimalObject()) return false;
      if (hasAnimalObject()) {
        if (!getAnimalObject()
            .equals(other.getAnimalObject())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + getCapacity();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasAnimalObject()) {
        hash = (37 * hash) + ANIMALOBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getAnimalObject().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static animals1.Animal.Tiger parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static animals1.Animal.Tiger parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static animals1.Animal.Tiger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static animals1.Animal.Tiger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static animals1.Animal.Tiger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static animals1.Animal.Tiger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static animals1.Animal.Tiger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static animals1.Animal.Tiger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static animals1.Animal.Tiger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static animals1.Animal.Tiger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static animals1.Animal.Tiger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static animals1.Animal.Tiger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(animals1.Animal.Tiger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code animals1.Animal.Tiger}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:animals1.Animal.Tiger)
        animals1.Animal.TigerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return animals1.Animal1.internal_static_animals1_Animal_Tiger_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return animals1.Animal1.internal_static_animals1_Animal_Tiger_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                animals1.Animal.Tiger.class, animals1.Animal.Tiger.Builder.class);
      }

      // Construct using animals1.Animal.Tiger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        capacity_ = 0;

        id_ = 0;

        if (animalObjectBuilder_ == null) {
          animalObject_ = null;
        } else {
          animalObject_ = null;
          animalObjectBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return animals1.Animal1.internal_static_animals1_Animal_Tiger_descriptor;
      }

      @java.lang.Override
      public animals1.Animal.Tiger getDefaultInstanceForType() {
        return animals1.Animal.Tiger.getDefaultInstance();
      }

      @java.lang.Override
      public animals1.Animal.Tiger build() {
        animals1.Animal.Tiger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public animals1.Animal.Tiger buildPartial() {
        animals1.Animal.Tiger result = new animals1.Animal.Tiger(this);
        result.type_ = type_;
        result.capacity_ = capacity_;
        result.id_ = id_;
        if (animalObjectBuilder_ == null) {
          result.animalObject_ = animalObject_;
        } else {
          result.animalObject_ = animalObjectBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof animals1.Animal.Tiger) {
          return mergeFrom((animals1.Animal.Tiger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(animals1.Animal.Tiger other) {
        if (other == animals1.Animal.Tiger.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getCapacity() != 0) {
          setCapacity(other.getCapacity());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasAnimalObject()) {
          mergeAnimalObject(other.getAnimalObject());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        animals1.Animal.Tiger parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (animals1.Animal.Tiger) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int capacity_ ;
      /**
       * <code>int32 capacity = 2;</code>
       * @return The capacity.
       */
      @java.lang.Override
      public int getCapacity() {
        return capacity_;
      }
      /**
       * <code>int32 capacity = 2;</code>
       * @param value The capacity to set.
       * @return This builder for chaining.
       */
      public Builder setCapacity(int value) {
        
        capacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 capacity = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCapacity() {
        
        capacity_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private animals1.Animal animalObject_;
      private com.google.protobuf.SingleFieldBuilderV3<
          animals1.Animal, animals1.Animal.Builder, animals1.AnimalOrBuilder> animalObjectBuilder_;
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       * @return Whether the animalObject field is set.
       */
      public boolean hasAnimalObject() {
        return animalObjectBuilder_ != null || animalObject_ != null;
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       * @return The animalObject.
       */
      public animals1.Animal getAnimalObject() {
        if (animalObjectBuilder_ == null) {
          return animalObject_ == null ? animals1.Animal.getDefaultInstance() : animalObject_;
        } else {
          return animalObjectBuilder_.getMessage();
        }
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      public Builder setAnimalObject(animals1.Animal value) {
        if (animalObjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          animalObject_ = value;
          onChanged();
        } else {
          animalObjectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      public Builder setAnimalObject(
          animals1.Animal.Builder builderForValue) {
        if (animalObjectBuilder_ == null) {
          animalObject_ = builderForValue.build();
          onChanged();
        } else {
          animalObjectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      public Builder mergeAnimalObject(animals1.Animal value) {
        if (animalObjectBuilder_ == null) {
          if (animalObject_ != null) {
            animalObject_ =
              animals1.Animal.newBuilder(animalObject_).mergeFrom(value).buildPartial();
          } else {
            animalObject_ = value;
          }
          onChanged();
        } else {
          animalObjectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      public Builder clearAnimalObject() {
        if (animalObjectBuilder_ == null) {
          animalObject_ = null;
          onChanged();
        } else {
          animalObject_ = null;
          animalObjectBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      public animals1.Animal.Builder getAnimalObjectBuilder() {
        
        onChanged();
        return getAnimalObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      public animals1.AnimalOrBuilder getAnimalObjectOrBuilder() {
        if (animalObjectBuilder_ != null) {
          return animalObjectBuilder_.getMessageOrBuilder();
        } else {
          return animalObject_ == null ?
              animals1.Animal.getDefaultInstance() : animalObject_;
        }
      }
      /**
       * <code>.animals1.Animal animalObject = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          animals1.Animal, animals1.Animal.Builder, animals1.AnimalOrBuilder> 
          getAnimalObjectFieldBuilder() {
        if (animalObjectBuilder_ == null) {
          animalObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              animals1.Animal, animals1.Animal.Builder, animals1.AnimalOrBuilder>(
                  getAnimalObject(),
                  getParentForChildren(),
                  isClean());
          animalObject_ = null;
        }
        return animalObjectBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:animals1.Animal.Tiger)
    }

    // @@protoc_insertion_point(class_scope:animals1.Animal.Tiger)
    private static final animals1.Animal.Tiger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new animals1.Animal.Tiger();
    }

    public static animals1.Animal.Tiger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tiger>
        PARSER = new com.google.protobuf.AbstractParser<Tiger>() {
      @java.lang.Override
      public Tiger parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tiger(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tiger> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tiger> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public animals1.Animal.Tiger getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HUNT_FIELD_NUMBER = 2;
  private boolean hunt_;
  /**
   * <code>bool hunt = 2;</code>
   * @return The hunt.
   */
  @java.lang.Override
  public boolean getHunt() {
    return hunt_;
  }

  public static final int TIGER_FIELD_NUMBER = 3;
  private animals1.Animal.Tiger tiger_;
  /**
   * <code>.animals1.Animal.Tiger tiger = 3;</code>
   * @return Whether the tiger field is set.
   */
  @java.lang.Override
  public boolean hasTiger() {
    return tiger_ != null;
  }
  /**
   * <code>.animals1.Animal.Tiger tiger = 3;</code>
   * @return The tiger.
   */
  @java.lang.Override
  public animals1.Animal.Tiger getTiger() {
    return tiger_ == null ? animals1.Animal.Tiger.getDefaultInstance() : tiger_;
  }
  /**
   * <code>.animals1.Animal.Tiger tiger = 3;</code>
   */
  @java.lang.Override
  public animals1.Animal.TigerOrBuilder getTigerOrBuilder() {
    return getTiger();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (hunt_ != false) {
      output.writeBool(2, hunt_);
    }
    if (tiger_ != null) {
      output.writeMessage(3, getTiger());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (hunt_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hunt_);
    }
    if (tiger_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTiger());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof animals1.Animal)) {
      return super.equals(obj);
    }
    animals1.Animal other = (animals1.Animal) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getHunt()
        != other.getHunt()) return false;
    if (hasTiger() != other.hasTiger()) return false;
    if (hasTiger()) {
      if (!getTiger()
          .equals(other.getTiger())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + HUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHunt());
    if (hasTiger()) {
      hash = (37 * hash) + TIGER_FIELD_NUMBER;
      hash = (53 * hash) + getTiger().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static animals1.Animal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals1.Animal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals1.Animal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals1.Animal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals1.Animal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static animals1.Animal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static animals1.Animal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static animals1.Animal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static animals1.Animal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static animals1.Animal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static animals1.Animal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static animals1.Animal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(animals1.Animal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code animals1.Animal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:animals1.Animal)
      animals1.AnimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return animals1.Animal1.internal_static_animals1_Animal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return animals1.Animal1.internal_static_animals1_Animal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              animals1.Animal.class, animals1.Animal.Builder.class);
    }

    // Construct using animals1.Animal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      hunt_ = false;

      if (tigerBuilder_ == null) {
        tiger_ = null;
      } else {
        tiger_ = null;
        tigerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return animals1.Animal1.internal_static_animals1_Animal_descriptor;
    }

    @java.lang.Override
    public animals1.Animal getDefaultInstanceForType() {
      return animals1.Animal.getDefaultInstance();
    }

    @java.lang.Override
    public animals1.Animal build() {
      animals1.Animal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public animals1.Animal buildPartial() {
      animals1.Animal result = new animals1.Animal(this);
      result.name_ = name_;
      result.hunt_ = hunt_;
      if (tigerBuilder_ == null) {
        result.tiger_ = tiger_;
      } else {
        result.tiger_ = tigerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof animals1.Animal) {
        return mergeFrom((animals1.Animal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(animals1.Animal other) {
      if (other == animals1.Animal.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getHunt() != false) {
        setHunt(other.getHunt());
      }
      if (other.hasTiger()) {
        mergeTiger(other.getTiger());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      animals1.Animal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (animals1.Animal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private boolean hunt_ ;
    /**
     * <code>bool hunt = 2;</code>
     * @return The hunt.
     */
    @java.lang.Override
    public boolean getHunt() {
      return hunt_;
    }
    /**
     * <code>bool hunt = 2;</code>
     * @param value The hunt to set.
     * @return This builder for chaining.
     */
    public Builder setHunt(boolean value) {
      
      hunt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hunt = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHunt() {
      
      hunt_ = false;
      onChanged();
      return this;
    }

    private animals1.Animal.Tiger tiger_;
    private com.google.protobuf.SingleFieldBuilderV3<
        animals1.Animal.Tiger, animals1.Animal.Tiger.Builder, animals1.Animal.TigerOrBuilder> tigerBuilder_;
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     * @return Whether the tiger field is set.
     */
    public boolean hasTiger() {
      return tigerBuilder_ != null || tiger_ != null;
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     * @return The tiger.
     */
    public animals1.Animal.Tiger getTiger() {
      if (tigerBuilder_ == null) {
        return tiger_ == null ? animals1.Animal.Tiger.getDefaultInstance() : tiger_;
      } else {
        return tigerBuilder_.getMessage();
      }
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    public Builder setTiger(animals1.Animal.Tiger value) {
      if (tigerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tiger_ = value;
        onChanged();
      } else {
        tigerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    public Builder setTiger(
        animals1.Animal.Tiger.Builder builderForValue) {
      if (tigerBuilder_ == null) {
        tiger_ = builderForValue.build();
        onChanged();
      } else {
        tigerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    public Builder mergeTiger(animals1.Animal.Tiger value) {
      if (tigerBuilder_ == null) {
        if (tiger_ != null) {
          tiger_ =
            animals1.Animal.Tiger.newBuilder(tiger_).mergeFrom(value).buildPartial();
        } else {
          tiger_ = value;
        }
        onChanged();
      } else {
        tigerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    public Builder clearTiger() {
      if (tigerBuilder_ == null) {
        tiger_ = null;
        onChanged();
      } else {
        tiger_ = null;
        tigerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    public animals1.Animal.Tiger.Builder getTigerBuilder() {
      
      onChanged();
      return getTigerFieldBuilder().getBuilder();
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    public animals1.Animal.TigerOrBuilder getTigerOrBuilder() {
      if (tigerBuilder_ != null) {
        return tigerBuilder_.getMessageOrBuilder();
      } else {
        return tiger_ == null ?
            animals1.Animal.Tiger.getDefaultInstance() : tiger_;
      }
    }
    /**
     * <code>.animals1.Animal.Tiger tiger = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        animals1.Animal.Tiger, animals1.Animal.Tiger.Builder, animals1.Animal.TigerOrBuilder> 
        getTigerFieldBuilder() {
      if (tigerBuilder_ == null) {
        tigerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            animals1.Animal.Tiger, animals1.Animal.Tiger.Builder, animals1.Animal.TigerOrBuilder>(
                getTiger(),
                getParentForChildren(),
                isClean());
        tiger_ = null;
      }
      return tigerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:animals1.Animal)
  }

  // @@protoc_insertion_point(class_scope:animals1.Animal)
  private static final animals1.Animal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new animals1.Animal();
  }

  public static animals1.Animal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Animal>
      PARSER = new com.google.protobuf.AbstractParser<Animal>() {
    @java.lang.Override
    public Animal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Animal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Animal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Animal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public animals1.Animal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

