// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance_1/animal1.proto

package animals1;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals1.Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool hunt = 2;</code>
   * @return The hunt.
   */
  boolean getHunt();

  /**
   * <code>.animals1.Animal.Tiger tiger = 3;</code>
   * @return Whether the tiger field is set.
   */
  boolean hasTiger();
  /**
   * <code>.animals1.Animal.Tiger tiger = 3;</code>
   * @return The tiger.
   */
  animals1.Animal.Tiger getTiger();
  /**
   * <code>.animals1.Animal.Tiger tiger = 3;</code>
   */
  animals1.Animal.TigerOrBuilder getTigerOrBuilder();
}
