// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

public final class CarOuterClass {
  private CarOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    java.util.List<CarOuterClass.Car.passList> 
        getPassList();
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    CarOuterClass.Car.passList getPass(int index);
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    int getPassCount();
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    java.util.List<? extends CarOuterClass.Car.passListOrBuilder> 
        getPassOrBuilderList();
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    CarOuterClass.Car.passListOrBuilder getPassOrBuilder(
        int index);
  }
  /**
   * <pre>
   * List&lt;List&lt;List&lt;int32&gt;&gt;&gt; pass;
   * </pre>
   *
   * Protobuf type {@code Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      pass_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Car();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pass_ = new java.util.ArrayList<CarOuterClass.Car.passList>();
                mutable_bitField0_ |= 0x00000001;
              }
              pass_.add(
                  input.readMessage(CarOuterClass.Car.passList.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pass_ = java.util.Collections.unmodifiableList(pass_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CarOuterClass.internal_static_Car_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CarOuterClass.internal_static_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CarOuterClass.Car.class, CarOuterClass.Car.Builder.class);
    }

    public interface passListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Car.passList)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      java.util.List<CarOuterClass.Car.passList.temList> 
          getTemList();
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      CarOuterClass.Car.passList.temList getTem(int index);
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      int getTemCount();
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      java.util.List<? extends CarOuterClass.Car.passList.temListOrBuilder> 
          getTemOrBuilderList();
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      CarOuterClass.Car.passList.temListOrBuilder getTemOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code Car.passList}
     */
    public static final class passList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Car.passList)
        passListOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use passList.newBuilder() to construct.
      private passList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private passList() {
        tem_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new passList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private passList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  tem_ = new java.util.ArrayList<CarOuterClass.Car.passList.temList>();
                  mutable_bitField0_ |= 0x00000001;
                }
                tem_.add(
                    input.readMessage(CarOuterClass.Car.passList.temList.parser(), extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            tem_ = java.util.Collections.unmodifiableList(tem_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CarOuterClass.internal_static_Car_passList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CarOuterClass.internal_static_Car_passList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CarOuterClass.Car.passList.class, CarOuterClass.Car.passList.Builder.class);
      }

      public interface temListOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Car.passList.temList)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated int32 temp = 1;</code>
         * @return A list containing the temp.
         */
        java.util.List<java.lang.Integer> getTempList();
        /**
         * <code>repeated int32 temp = 1;</code>
         * @return The count of temp.
         */
        int getTempCount();
        /**
         * <code>repeated int32 temp = 1;</code>
         * @param index The index of the element to return.
         * @return The temp at the given index.
         */
        int getTemp(int index);
      }
      /**
       * Protobuf type {@code Car.passList.temList}
       */
      public static final class temList extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Car.passList.temList)
          temListOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use temList.newBuilder() to construct.
        private temList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private temList() {
          temp_ = emptyIntList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
          return new temList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        private temList(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          this();
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                    temp_ = newIntList();
                    mutable_bitField0_ |= 0x00000001;
                  }
                  temp_.addInt(input.readInt32());
                  break;
                }
                case 10: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                    temp_ = newIntList();
                    mutable_bitField0_ |= 0x00000001;
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    temp_.addInt(input.readInt32());
                  }
                  input.popLimit(limit);
                  break;
                }
                default: {
                  if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
          } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
              temp_.makeImmutable(); // C
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CarOuterClass.internal_static_Car_passList_temList_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CarOuterClass.internal_static_Car_passList_temList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CarOuterClass.Car.passList.temList.class, CarOuterClass.Car.passList.temList.Builder.class);
        }

        public static final int TEMP_FIELD_NUMBER = 1;
        private com.google.protobuf.Internal.IntList temp_;
        /**
         * <code>repeated int32 temp = 1;</code>
         * @return A list containing the temp.
         */
        @java.lang.Override
        public java.util.List<java.lang.Integer>
            getTempList() {
          return temp_;
        }
        /**
         * <code>repeated int32 temp = 1;</code>
         * @return The count of temp.
         */
        public int getTempCount() {
          return temp_.size();
        }
        /**
         * <code>repeated int32 temp = 1;</code>
         * @param index The index of the element to return.
         * @return The temp at the given index.
         */
        public int getTemp(int index) {
          return temp_.getInt(index);
        }
        private int tempMemoizedSerializedSize = -1;

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (getTempList().size() > 0) {
            output.writeUInt32NoTag(10);
            output.writeUInt32NoTag(tempMemoizedSerializedSize);
          }
          for (int i = 0; i < temp_.size(); i++) {
            output.writeInt32NoTag(temp_.getInt(i));
          }
          unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          {
            int dataSize = 0;
            for (int i = 0; i < temp_.size(); i++) {
              dataSize += com.google.protobuf.CodedOutputStream
                .computeInt32SizeNoTag(temp_.getInt(i));
            }
            size += dataSize;
            if (!getTempList().isEmpty()) {
              size += 1;
              size += com.google.protobuf.CodedOutputStream
                  .computeInt32SizeNoTag(dataSize);
            }
            tempMemoizedSerializedSize = dataSize;
          }
          size += unknownFields.getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof CarOuterClass.Car.passList.temList)) {
            return super.equals(obj);
          }
          CarOuterClass.Car.passList.temList other = (CarOuterClass.Car.passList.temList) obj;

          if (!getTempList()
              .equals(other.getTempList())) return false;
          if (!unknownFields.equals(other.unknownFields)) return false;
          return true;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          if (getTempCount() > 0) {
            hash = (37 * hash) + TEMP_FIELD_NUMBER;
            hash = (53 * hash) + getTempList().hashCode();
          }
          hash = (29 * hash) + unknownFields.hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static CarOuterClass.Car.passList.temList parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static CarOuterClass.Car.passList.temList parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static CarOuterClass.Car.passList.temList parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static CarOuterClass.Car.passList.temList parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(CarOuterClass.Car.passList.temList prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code Car.passList.temList}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Car.passList.temList)
            CarOuterClass.Car.passList.temListOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return CarOuterClass.internal_static_Car_passList_temList_descriptor;
          }

          @java.lang.Override
          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return CarOuterClass.internal_static_Car_passList_temList_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    CarOuterClass.Car.passList.temList.class, CarOuterClass.Car.passList.temList.Builder.class);
          }

          // Construct using CarOuterClass.Car.passList.temList.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
          }
          @java.lang.Override
          public Builder clear() {
            super.clear();
            temp_ = emptyIntList();
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
          }

          @java.lang.Override
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return CarOuterClass.internal_static_Car_passList_temList_descriptor;
          }

          @java.lang.Override
          public CarOuterClass.Car.passList.temList getDefaultInstanceForType() {
            return CarOuterClass.Car.passList.temList.getDefaultInstance();
          }

          @java.lang.Override
          public CarOuterClass.Car.passList.temList build() {
            CarOuterClass.Car.passList.temList result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          @java.lang.Override
          public CarOuterClass.Car.passList.temList buildPartial() {
            CarOuterClass.Car.passList.temList result = new CarOuterClass.Car.passList.temList(this);
            int from_bitField0_ = bitField0_;
            if (((bitField0_ & 0x00000001) != 0)) {
              temp_.makeImmutable();
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.temp_ = temp_;
            onBuilt();
            return result;
          }

          @java.lang.Override
          public Builder clone() {
            return super.clone();
          }
          @java.lang.Override
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return super.setField(field, value);
          }
          @java.lang.Override
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
          }
          @java.lang.Override
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
          }
          @java.lang.Override
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
          }
          @java.lang.Override
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return super.addRepeatedField(field, value);
          }
          @java.lang.Override
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof CarOuterClass.Car.passList.temList) {
              return mergeFrom((CarOuterClass.Car.passList.temList)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(CarOuterClass.Car.passList.temList other) {
            if (other == CarOuterClass.Car.passList.temList.getDefaultInstance()) return this;
            if (!other.temp_.isEmpty()) {
              if (temp_.isEmpty()) {
                temp_ = other.temp_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureTempIsMutable();
                temp_.addAll(other.temp_);
              }
              onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
          }

          @java.lang.Override
          public final boolean isInitialized() {
            return true;
          }

          @java.lang.Override
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            CarOuterClass.Car.passList.temList parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (CarOuterClass.Car.passList.temList) e.getUnfinishedMessage();
              throw e.unwrapIOException();
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          private com.google.protobuf.Internal.IntList temp_ = emptyIntList();
          private void ensureTempIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
              temp_ = mutableCopy(temp_);
              bitField0_ |= 0x00000001;
             }
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @return A list containing the temp.
           */
          public java.util.List<java.lang.Integer>
              getTempList() {
            return ((bitField0_ & 0x00000001) != 0) ?
                     java.util.Collections.unmodifiableList(temp_) : temp_;
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @return The count of temp.
           */
          public int getTempCount() {
            return temp_.size();
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @param index The index of the element to return.
           * @return The temp at the given index.
           */
          public int getTemp(int index) {
            return temp_.getInt(index);
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @param index The index to set the value at.
           * @param value The temp to set.
           * @return This builder for chaining.
           */
          public Builder setTemp(
              int index, int value) {
            ensureTempIsMutable();
            temp_.setInt(index, value);
            onChanged();
            return this;
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @param value The temp to add.
           * @return This builder for chaining.
           */
          public Builder addTemp(int value) {
            ensureTempIsMutable();
            temp_.addInt(value);
            onChanged();
            return this;
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @param values The temp to add.
           * @return This builder for chaining.
           */
          public Builder addAllTemp(
              java.lang.Iterable<? extends java.lang.Integer> values) {
            ensureTempIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, temp_);
            onChanged();
            return this;
          }
          /**
           * <code>repeated int32 temp = 1;</code>
           * @return This builder for chaining.
           */
          public Builder clearTemp() {
            temp_ = emptyIntList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
          }
          @java.lang.Override
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
          }

          @java.lang.Override
          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:Car.passList.temList)
        }

        // @@protoc_insertion_point(class_scope:Car.passList.temList)
        private static final CarOuterClass.Car.passList.temList DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new CarOuterClass.Car.passList.temList();
        }

        public static CarOuterClass.Car.passList.temList getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<temList>
            PARSER = new com.google.protobuf.AbstractParser<temList>() {
          @java.lang.Override
          public temList parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new temList(input, extensionRegistry);
          }
        };

        public static com.google.protobuf.Parser<temList> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<temList> getParserForType() {
          return PARSER;
        }

        @java.lang.Override
        public CarOuterClass.Car.passList.temList getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      public static final int TEM_FIELD_NUMBER = 1;
      private java.util.List<CarOuterClass.Car.passList.temList> tem_;
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      @java.lang.Override
      public java.util.List<CarOuterClass.Car.passList.temList> getTemList() {
        return tem_;
      }
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      @java.lang.Override
      public java.util.List<? extends CarOuterClass.Car.passList.temListOrBuilder> 
          getTemOrBuilderList() {
        return tem_;
      }
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      @java.lang.Override
      public int getTemCount() {
        return tem_.size();
      }
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      @java.lang.Override
      public CarOuterClass.Car.passList.temList getTem(int index) {
        return tem_.get(index);
      }
      /**
       * <code>repeated .Car.passList.temList tem = 1;</code>
       */
      @java.lang.Override
      public CarOuterClass.Car.passList.temListOrBuilder getTemOrBuilder(
          int index) {
        return tem_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < tem_.size(); i++) {
          output.writeMessage(1, tem_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < tem_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, tem_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof CarOuterClass.Car.passList)) {
          return super.equals(obj);
        }
        CarOuterClass.Car.passList other = (CarOuterClass.Car.passList) obj;

        if (!getTemList()
            .equals(other.getTemList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getTemCount() > 0) {
          hash = (37 * hash) + TEM_FIELD_NUMBER;
          hash = (53 * hash) + getTemList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static CarOuterClass.Car.passList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CarOuterClass.Car.passList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CarOuterClass.Car.passList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CarOuterClass.Car.passList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CarOuterClass.Car.passList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CarOuterClass.Car.passList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CarOuterClass.Car.passList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CarOuterClass.Car.passList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static CarOuterClass.Car.passList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static CarOuterClass.Car.passList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static CarOuterClass.Car.passList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CarOuterClass.Car.passList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(CarOuterClass.Car.passList prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Car.passList}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Car.passList)
          CarOuterClass.Car.passListOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CarOuterClass.internal_static_Car_passList_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CarOuterClass.internal_static_Car_passList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CarOuterClass.Car.passList.class, CarOuterClass.Car.passList.Builder.class);
        }

        // Construct using CarOuterClass.Car.passList.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getTemFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (temBuilder_ == null) {
            tem_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            temBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CarOuterClass.internal_static_Car_passList_descriptor;
        }

        @java.lang.Override
        public CarOuterClass.Car.passList getDefaultInstanceForType() {
          return CarOuterClass.Car.passList.getDefaultInstance();
        }

        @java.lang.Override
        public CarOuterClass.Car.passList build() {
          CarOuterClass.Car.passList result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public CarOuterClass.Car.passList buildPartial() {
          CarOuterClass.Car.passList result = new CarOuterClass.Car.passList(this);
          int from_bitField0_ = bitField0_;
          if (temBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0)) {
              tem_ = java.util.Collections.unmodifiableList(tem_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.tem_ = tem_;
          } else {
            result.tem_ = temBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CarOuterClass.Car.passList) {
            return mergeFrom((CarOuterClass.Car.passList)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CarOuterClass.Car.passList other) {
          if (other == CarOuterClass.Car.passList.getDefaultInstance()) return this;
          if (temBuilder_ == null) {
            if (!other.tem_.isEmpty()) {
              if (tem_.isEmpty()) {
                tem_ = other.tem_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureTemIsMutable();
                tem_.addAll(other.tem_);
              }
              onChanged();
            }
          } else {
            if (!other.tem_.isEmpty()) {
              if (temBuilder_.isEmpty()) {
                temBuilder_.dispose();
                temBuilder_ = null;
                tem_ = other.tem_;
                bitField0_ = (bitField0_ & ~0x00000001);
                temBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getTemFieldBuilder() : null;
              } else {
                temBuilder_.addAllMessages(other.tem_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CarOuterClass.Car.passList parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CarOuterClass.Car.passList) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<CarOuterClass.Car.passList.temList> tem_ =
          java.util.Collections.emptyList();
        private void ensureTemIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            tem_ = new java.util.ArrayList<CarOuterClass.Car.passList.temList>(tem_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            CarOuterClass.Car.passList.temList, CarOuterClass.Car.passList.temList.Builder, CarOuterClass.Car.passList.temListOrBuilder> temBuilder_;

        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public java.util.List<CarOuterClass.Car.passList.temList> getTemList() {
          if (temBuilder_ == null) {
            return java.util.Collections.unmodifiableList(tem_);
          } else {
            return temBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public int getTemCount() {
          if (temBuilder_ == null) {
            return tem_.size();
          } else {
            return temBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public CarOuterClass.Car.passList.temList getTem(int index) {
          if (temBuilder_ == null) {
            return tem_.get(index);
          } else {
            return temBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder setTem(
            int index, CarOuterClass.Car.passList.temList value) {
          if (temBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureTemIsMutable();
            tem_.set(index, value);
            onChanged();
          } else {
            temBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder setTem(
            int index, CarOuterClass.Car.passList.temList.Builder builderForValue) {
          if (temBuilder_ == null) {
            ensureTemIsMutable();
            tem_.set(index, builderForValue.build());
            onChanged();
          } else {
            temBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder addTem(CarOuterClass.Car.passList.temList value) {
          if (temBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureTemIsMutable();
            tem_.add(value);
            onChanged();
          } else {
            temBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder addTem(
            int index, CarOuterClass.Car.passList.temList value) {
          if (temBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureTemIsMutable();
            tem_.add(index, value);
            onChanged();
          } else {
            temBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder addTem(
            CarOuterClass.Car.passList.temList.Builder builderForValue) {
          if (temBuilder_ == null) {
            ensureTemIsMutable();
            tem_.add(builderForValue.build());
            onChanged();
          } else {
            temBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder addTem(
            int index, CarOuterClass.Car.passList.temList.Builder builderForValue) {
          if (temBuilder_ == null) {
            ensureTemIsMutable();
            tem_.add(index, builderForValue.build());
            onChanged();
          } else {
            temBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder addAllTem(
            java.lang.Iterable<? extends CarOuterClass.Car.passList.temList> values) {
          if (temBuilder_ == null) {
            ensureTemIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, tem_);
            onChanged();
          } else {
            temBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder clearTem() {
          if (temBuilder_ == null) {
            tem_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            temBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public Builder removeTem(int index) {
          if (temBuilder_ == null) {
            ensureTemIsMutable();
            tem_.remove(index);
            onChanged();
          } else {
            temBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public CarOuterClass.Car.passList.temList.Builder getTemBuilder(
            int index) {
          return getTemFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public CarOuterClass.Car.passList.temListOrBuilder getTemOrBuilder(
            int index) {
          if (temBuilder_ == null) {
            return tem_.get(index);  } else {
            return temBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public java.util.List<? extends CarOuterClass.Car.passList.temListOrBuilder> 
             getTemOrBuilderList() {
          if (temBuilder_ != null) {
            return temBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(tem_);
          }
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public CarOuterClass.Car.passList.temList.Builder addTemBuilder() {
          return getTemFieldBuilder().addBuilder(
              CarOuterClass.Car.passList.temList.getDefaultInstance());
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public CarOuterClass.Car.passList.temList.Builder addTemBuilder(
            int index) {
          return getTemFieldBuilder().addBuilder(
              index, CarOuterClass.Car.passList.temList.getDefaultInstance());
        }
        /**
         * <code>repeated .Car.passList.temList tem = 1;</code>
         */
        public java.util.List<CarOuterClass.Car.passList.temList.Builder> 
             getTemBuilderList() {
          return getTemFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            CarOuterClass.Car.passList.temList, CarOuterClass.Car.passList.temList.Builder, CarOuterClass.Car.passList.temListOrBuilder> 
            getTemFieldBuilder() {
          if (temBuilder_ == null) {
            temBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                CarOuterClass.Car.passList.temList, CarOuterClass.Car.passList.temList.Builder, CarOuterClass.Car.passList.temListOrBuilder>(
                    tem_,
                    ((bitField0_ & 0x00000001) != 0),
                    getParentForChildren(),
                    isClean());
            tem_ = null;
          }
          return temBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Car.passList)
      }

      // @@protoc_insertion_point(class_scope:Car.passList)
      private static final CarOuterClass.Car.passList DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new CarOuterClass.Car.passList();
      }

      public static CarOuterClass.Car.passList getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<passList>
          PARSER = new com.google.protobuf.AbstractParser<passList>() {
        @java.lang.Override
        public passList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new passList(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<passList> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<passList> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public CarOuterClass.Car.passList getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PASS_FIELD_NUMBER = 1;
    private java.util.List<CarOuterClass.Car.passList> pass_;
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    @java.lang.Override
    public java.util.List<CarOuterClass.Car.passList> getPassList() {
      return pass_;
    }
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends CarOuterClass.Car.passListOrBuilder> 
        getPassOrBuilderList() {
      return pass_;
    }
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    @java.lang.Override
    public int getPassCount() {
      return pass_.size();
    }
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    @java.lang.Override
    public CarOuterClass.Car.passList getPass(int index) {
      return pass_.get(index);
    }
    /**
     * <code>repeated .Car.passList pass = 1;</code>
     */
    @java.lang.Override
    public CarOuterClass.Car.passListOrBuilder getPassOrBuilder(
        int index) {
      return pass_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pass_.size(); i++) {
        output.writeMessage(1, pass_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pass_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pass_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CarOuterClass.Car)) {
        return super.equals(obj);
      }
      CarOuterClass.Car other = (CarOuterClass.Car) obj;

      if (!getPassList()
          .equals(other.getPassList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPassCount() > 0) {
        hash = (37 * hash) + PASS_FIELD_NUMBER;
        hash = (53 * hash) + getPassList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CarOuterClass.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CarOuterClass.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CarOuterClass.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CarOuterClass.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CarOuterClass.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CarOuterClass.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CarOuterClass.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CarOuterClass.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CarOuterClass.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CarOuterClass.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CarOuterClass.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CarOuterClass.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CarOuterClass.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * List&lt;List&lt;List&lt;int32&gt;&gt;&gt; pass;
     * </pre>
     *
     * Protobuf type {@code Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Car)
        CarOuterClass.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CarOuterClass.internal_static_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CarOuterClass.internal_static_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CarOuterClass.Car.class, CarOuterClass.Car.Builder.class);
      }

      // Construct using CarOuterClass.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPassFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (passBuilder_ == null) {
          pass_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          passBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CarOuterClass.internal_static_Car_descriptor;
      }

      @java.lang.Override
      public CarOuterClass.Car getDefaultInstanceForType() {
        return CarOuterClass.Car.getDefaultInstance();
      }

      @java.lang.Override
      public CarOuterClass.Car build() {
        CarOuterClass.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CarOuterClass.Car buildPartial() {
        CarOuterClass.Car result = new CarOuterClass.Car(this);
        int from_bitField0_ = bitField0_;
        if (passBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            pass_ = java.util.Collections.unmodifiableList(pass_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pass_ = pass_;
        } else {
          result.pass_ = passBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CarOuterClass.Car) {
          return mergeFrom((CarOuterClass.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CarOuterClass.Car other) {
        if (other == CarOuterClass.Car.getDefaultInstance()) return this;
        if (passBuilder_ == null) {
          if (!other.pass_.isEmpty()) {
            if (pass_.isEmpty()) {
              pass_ = other.pass_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePassIsMutable();
              pass_.addAll(other.pass_);
            }
            onChanged();
          }
        } else {
          if (!other.pass_.isEmpty()) {
            if (passBuilder_.isEmpty()) {
              passBuilder_.dispose();
              passBuilder_ = null;
              pass_ = other.pass_;
              bitField0_ = (bitField0_ & ~0x00000001);
              passBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPassFieldBuilder() : null;
            } else {
              passBuilder_.addAllMessages(other.pass_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CarOuterClass.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CarOuterClass.Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<CarOuterClass.Car.passList> pass_ =
        java.util.Collections.emptyList();
      private void ensurePassIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pass_ = new java.util.ArrayList<CarOuterClass.Car.passList>(pass_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CarOuterClass.Car.passList, CarOuterClass.Car.passList.Builder, CarOuterClass.Car.passListOrBuilder> passBuilder_;

      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public java.util.List<CarOuterClass.Car.passList> getPassList() {
        if (passBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pass_);
        } else {
          return passBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public int getPassCount() {
        if (passBuilder_ == null) {
          return pass_.size();
        } else {
          return passBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public CarOuterClass.Car.passList getPass(int index) {
        if (passBuilder_ == null) {
          return pass_.get(index);
        } else {
          return passBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder setPass(
          int index, CarOuterClass.Car.passList value) {
        if (passBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassIsMutable();
          pass_.set(index, value);
          onChanged();
        } else {
          passBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder setPass(
          int index, CarOuterClass.Car.passList.Builder builderForValue) {
        if (passBuilder_ == null) {
          ensurePassIsMutable();
          pass_.set(index, builderForValue.build());
          onChanged();
        } else {
          passBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder addPass(CarOuterClass.Car.passList value) {
        if (passBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassIsMutable();
          pass_.add(value);
          onChanged();
        } else {
          passBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder addPass(
          int index, CarOuterClass.Car.passList value) {
        if (passBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassIsMutable();
          pass_.add(index, value);
          onChanged();
        } else {
          passBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder addPass(
          CarOuterClass.Car.passList.Builder builderForValue) {
        if (passBuilder_ == null) {
          ensurePassIsMutable();
          pass_.add(builderForValue.build());
          onChanged();
        } else {
          passBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder addPass(
          int index, CarOuterClass.Car.passList.Builder builderForValue) {
        if (passBuilder_ == null) {
          ensurePassIsMutable();
          pass_.add(index, builderForValue.build());
          onChanged();
        } else {
          passBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder addAllPass(
          java.lang.Iterable<? extends CarOuterClass.Car.passList> values) {
        if (passBuilder_ == null) {
          ensurePassIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pass_);
          onChanged();
        } else {
          passBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder clearPass() {
        if (passBuilder_ == null) {
          pass_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          passBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public Builder removePass(int index) {
        if (passBuilder_ == null) {
          ensurePassIsMutable();
          pass_.remove(index);
          onChanged();
        } else {
          passBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public CarOuterClass.Car.passList.Builder getPassBuilder(
          int index) {
        return getPassFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public CarOuterClass.Car.passListOrBuilder getPassOrBuilder(
          int index) {
        if (passBuilder_ == null) {
          return pass_.get(index);  } else {
          return passBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public java.util.List<? extends CarOuterClass.Car.passListOrBuilder> 
           getPassOrBuilderList() {
        if (passBuilder_ != null) {
          return passBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pass_);
        }
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public CarOuterClass.Car.passList.Builder addPassBuilder() {
        return getPassFieldBuilder().addBuilder(
            CarOuterClass.Car.passList.getDefaultInstance());
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public CarOuterClass.Car.passList.Builder addPassBuilder(
          int index) {
        return getPassFieldBuilder().addBuilder(
            index, CarOuterClass.Car.passList.getDefaultInstance());
      }
      /**
       * <code>repeated .Car.passList pass = 1;</code>
       */
      public java.util.List<CarOuterClass.Car.passList.Builder> 
           getPassBuilderList() {
        return getPassFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CarOuterClass.Car.passList, CarOuterClass.Car.passList.Builder, CarOuterClass.Car.passListOrBuilder> 
          getPassFieldBuilder() {
        if (passBuilder_ == null) {
          passBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CarOuterClass.Car.passList, CarOuterClass.Car.passList.Builder, CarOuterClass.Car.passListOrBuilder>(
                  pass_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          pass_ = null;
        }
        return passBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Car)
    }

    // @@protoc_insertion_point(class_scope:Car)
    private static final CarOuterClass.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CarOuterClass.Car();
    }

    public static CarOuterClass.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CarOuterClass.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_passList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Car_passList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_passList_temList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Car_passList_temList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcar.proto\"k\n\003Car\022\033\n\004pass\030\001 \003(\0132\r.Car.p" +
      "assList\032G\n\010passList\022\"\n\003tem\030\001 \003(\0132\025.Car.p" +
      "assList.temList\032\027\n\007temList\022\014\n\004temp\030\001 \003(\005" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Car_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Car_descriptor,
        new java.lang.String[] { "Pass", });
    internal_static_Car_passList_descriptor =
      internal_static_Car_descriptor.getNestedTypes().get(0);
    internal_static_Car_passList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Car_passList_descriptor,
        new java.lang.String[] { "Tem", });
    internal_static_Car_passList_temList_descriptor =
      internal_static_Car_passList_descriptor.getNestedTypes().get(0);
    internal_static_Car_passList_temList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Car_passList_temList_descriptor,
        new java.lang.String[] { "Temp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
